# ====================================================================
# NetworkMaintenance-Pro v2.0.0 - Main Maintenance Controller
# ====================================================================
# Description: Main entry point for all maintenance operations
# ====================================================================

param(
    [string]$Mode = "Full",
    [string]$ConfigPath = "C:\NetworkMaintenance\Config\Config.json",
    [string]$LogPath = "C:\NetworkMaintenance\Logs",
    [switch]$DryRun,
    [switch]$AutoHeal,
    [switch]$Continuous,
    [switch]$Report,
    [switch]$Schedule,
    [string]$Target = ""
)

$Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$LogFile = "$LogPath\Maintenance_$(Get-Date -Format 'yyyyMMdd').log"

function Write-Log {
    param([string]$Message, [string]$Level = "INFO")
    $entry = "[$Timestamp][$Level] $Message"
    Add-Content -Path $LogFile -Value $entry -Force
    switch ($Level) {
        "ERROR" { Write-Host $entry -ForegroundColor Red }
        "WARN" { Write-Host $entry -ForegroundColor Yellow }
        "SUCCESS" { Write-Host $entry -ForegroundColor Green }
        "ACTION" { Write-Host $entry -ForegroundColor Cyan }
        "HEADER" { Write-Host $entry -ForegroundColor Magenta }
        default { Write-Host $entry -ForegroundColor White }
    }
}

function Show-Banner {
    Write-Log "============================================" "HEADER"
    Write-Log "  NetworkMaintenance-Pro v2.0.0" "HEADER"
    Write-Log "  Professional Network Maintenance System" "HEADER"
    Write-Log "============================================" "HEADER"
    Write-Log "Mode: $Mode | Time: $Timestamp" "HEADER"
    Write-Log ""
}

function Run-Diagnostics {
    Write-Log "=== Running Diagnostics ===" "ACTION"
    & "C:\NetworkMaintenance\Scripts\01_Diagnostics.ps1" -ConfigPath $ConfigPath -LogPath $LogPath
    Write-Log "Diagnostics Complete!" "SUCCESS"
}

function Run-Optimization {
    Write-Log "=== Running Optimization ===" "ACTION"
    & "C:\NetworkMaintenance\Scripts\02_Optimization.ps1" -ConfigPath $ConfigPath -LogPath $LogPath -DryRun:$DryRun -ForceApply:(!$DryRun)
    Write-Log "Optimization Complete!" "SUCCESS"
}

function Run-SafeCleaning {
    Write-Log "=== Running Safe Cleaning (SCE Engine) ===" "ACTION"
    $enterpriseConfig = "C:\NetworkMaintenance\Config\EnterpriseConfig.json"
    $sceParams = @{ ConfigPath = $enterpriseConfig; SafetyLevel = "Balanced" }
    if ($DryRun) { $sceParams.DryRun = $true }
    & "C:\NetworkMaintenance\Scripts\Engines\SCE-Engine.ps1" @sceParams
    Write-Log "Safe Cleaning Complete!" "SUCCESS"
}

function Run-AutoHeal {
    Write-Log "=== Running Auto-Heal ===" "ACTION"
    & "C:\NetworkMaintenance\Scripts\03_AutoHeal.ps1" -ConfigPath $ConfigPath -LogPath $LogPath
    Write-Log "Auto-Heal Complete!" "SUCCESS"
}

function Run-Monitoring {
    Write-Log "=== Running Monitoring ===" "ACTION"
    & "C:\NetworkMaintenance\Scripts\04_Monitoring.ps1" -ConfigPath $ConfigPath -LogPath $LogPath -Continuous:$Continuous
    Write-Log "Monitoring Complete!" "SUCCESS"
}

function Generate-Report {
    Write-Log "=== Generating Report ===" "ACTION"
    
    $reportDate = Get-Date -Format "yyyy-MM-dd"
    $reportFile = "$LogPath\Reports\Report_$reportDate.md"
    
    $content = @"
# Network Maintenance Report - $reportDate

## System Overview
- **System**: NetworkMaintenance-Pro v2.0.0
- **Generated**: $Timestamp
- **Mode**: $Mode

## Diagnostic Summary
$(Get-Content "$LogPath\Diagnostic_$(Get-Date -Format 'yyyyMMdd').log" -ErrorAction SilentlyContinue | Out-String)

## Optimization Summary
$(Get-Content "$LogPath\Optimization_$(Get-Date -Format 'yyyyMMdd').log" -ErrorAction SilentlyContinue | Out-String)

## Auto-Heal Summary
$(Get-Content "$LogPath\AutoHeal_$(Get-Date -Format 'yyyyMMdd').log" -ErrorAction SilentlyContinue | Out-String)

## Recommendations
- Run diagnostics weekly to maintain optimal performance
- Apply optimization monthly or after major network changes
- Enable auto-heal for continuous protection
- Monitor network metrics daily

## System Health Score
$(Get-HealthScore)

---
*Generated by NetworkMaintenance-Pro v2.0.0*
"@

    $content | Set-Content $reportFile -Force
    Write-Log "Report saved to: $reportFile" "SUCCESS"
}

function Get-HealthScore {
    $score = 100
    
    # Check latency
    $pingOutput = cmd /c "ping -n 5 $($Config.Diagnostic.PingTarget)" 2>nul
    $latencies = @()
    foreach ($line in $pingOutput) {
        if ($line -match "time=(\d+)ms") { $latencies += [int]$matches[1] }
    }
    
    if ($latencies.Count -gt 0) {
        $avg = ($latencies | Measure-Object -Average).Average
        if ($avg -gt $Config.Network.CriticalLatencyMs) { $score -= 40 }
        elseif ($avg -gt $Config.Network.WarningLatencyMs) { $score -= 20 }
        elseif ($avg -gt $Config.Network.ExpectedLatencyMs) { $score -= 10 }
    }
    
    # Check DNS
    try {
        Resolve-DnsName "google.com" -Server 1.1.1.1 -QuickTimeout -ErrorAction Stop | Out-Null
    } catch {
        $score -= 30
    }
    
    # Check if optimization applied
    if (Test-Path "C:\NetworkMaintenance\Config\LastOptimization.json") {
        $score += 5
    }
    
    return "Score: $score/100"
}

function Invoke-Scheduler {
    Write-Log "=== Setting Up Scheduler ===" "ACTION"
    
    # Create scheduled task for daily maintenance
    $taskName = "NetworkMaintenance-Pro"
    $taskCommand = "powershell.exe -ExecutionPolicy Bypass -File C:\NetworkMaintenance\Scripts\05_Maintenance.ps1 -Mode Daily -ConfigPath $ConfigPath"
    
    Write-Log "Creating scheduled task: $taskName" "ACTION"
    Write-Log "Command: $taskCommand" "ACTION"
    
    # Register the task (requires admin privileges)
    # schtasks /create /tn $taskName /tr $taskCommand /sc daily /st 06:00 /ru SYSTEM
    
    Write-Log "Scheduler configured!" "SUCCESS"
}

# Main execution
Show-Banner

switch ($Mode.ToLower()) {
    "diagnostics" { Run-Diagnostics }
    "optimize" { Run-Optimization }
    "heal" { Run-AutoHeal }
    "monitor" { Run-Monitoring }
    "report" { Generate-Report }
    "scheduler" { Invoke-Scheduler }
    "clean" { Run-SafeCleaning }
    "full" {
        Run-Diagnostics
        if ($AutoHeal) { Run-AutoHeal }
        Run-Optimization
        Run-SafeCleaning
        Run-Monitoring
        Generate-Report
    }
    default {
        Write-Log "Unknown mode: $Mode" "ERROR"
        Write-Log "Valid modes: diagnostics, optimize, heal, clean, monitor, report, scheduler, full" "WARN"
    }
}

Write-Log ""
Write-Log "============================================" "HEADER"
Write-Log "  Maintenance Complete" "HEADER"
Write-Log "============================================" "HEADER"
